# Generated by Django 2.0.1 on 2018-01-06 20:01

import apiApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.FileField(upload_to=apiApp.models.upload_location)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiApp.Student')),
            ],
        ),
        migrations.RemoveField(
            model_name='studentvideo',
            name='student_id',
        ),
        migrations.AddField(
            model_name='course',
            name='enrollment_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='StudentVideo',
        ),
    ]
